# Generated by Django 4.0.4 on 2022-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default='admin', max_length=64),
            preserve_default=False,
        ),
    ]
